### ISSUE TITLE
As plugin for Open-Assistant.io/gpt4all

### ISSUE THREAD

**Issue by vasnt** [kesor/chatgpt-code-plugin#2]
Is it possible to add this as plugin at https://open-assistant.io/ or gpt4all ?

**Comment by kesor** [comment]
I tried looking around OpenAssistant, and it does not seem like they support localhost plugins. So you will need to publish your localhost plugin to be available on the internet somehow.

I used ngrok.com to make my localhost port 3000 become available on the internet.

Then on the OpenAssistant website you can add the plugin by using your ngrok generated address, and including the path for the ai-plugin.json file. Like so - `https://569c-84-229-37-68.ngrok-free.app/.well-known/ai-plugin.json`

But before you do, you will also need to change the `ai-plugin.json` file so that it has your ngrok url specified for the `openapi.yaml`. So in my case I had to change it to say `{ "api": { "type": "openapi", "url": "https://569c-84-229-37-68.ngrok-free.app/openapi.yaml" } }`

It seemed to work ... but I couldn't get a single response from OpenAssistant at all, probably because there is a queue, and it just takes forever to get anything to work over there.

So in theory, everything works. But in practice, nothing does.
